export default {
  defaultPath: "/",
  basename: "/",
  // defaultPath: "/admin/",
  // basename: "/admin/",
  layout: "vertical",
  subLayout: "",
  collapseMenu: false,
  layoutType: " menu-dark",
  headerBackColor: "background-grd-blue",
  rtlLayout: false,
  navFixedLayout: true,
  headerFixedLayout: false,
  boxLayout: false,
  mode: "DEV", //PRO DEV TEST
  entity: 2,
  entityName: "SEGUNDA ESPECIALIDAD FCS",
  hostPro: "http://localhost:8899/api/",
  // hostPro: "https://asefcs.unsm.edu.pe/api/",
};
